config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/', to: "home#index", as: :home
  get 'tutorial', to: "home#tutorial", as: :tutorial

  get    '/signup',   to: 'users#new', as: :signup
  post   '/signup',   to: 'users#create'

  get    '/login',   to: 'sessions#new', as: :login
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy', as: :logout

  get '/experiment', to: "home#experiment", as: :experiment
  get '/rate', to: "home#rate", as: :rate
  post '/rate', to: "home#submit_rating", as: :submit_rating
  get '/compare', to: "home#compare", as: :compare
  post '/compare', to: "home#submit_comparison", as: :submit_comparison

  get '/completed', to: "home#completed", as: :completed
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_user, only: [:experiment, :rate, :submit_rating, :compare, :submit_comparison]
  before_action :check_completed, only: [:experiment, :rate, :submit_rating, :compare, :submit_comparison]
  before_action :set_function, only: [:rate, :submit_rating, :compare, :submit_comparison]
  before_action :set_comment, only: [:rate, :submit_rating]
  before_action :set_comments, only: [:compare, :submit_comparison]

  def index
    if current_user
      redirect_to :experiment
    end
  end

  def tutorial
  end

  def experiment
    if @user.current_phase == "compare"
      redirect_to :compare
    else
      redirect_to :rate
    end
  end

  def rate
    if @user.current_phase == "compare"
      redirect_to :compare
    end
  end

  def demo
    
  end

  def compare
    if @user.current_phase != "compare"
      redirect_to :rate
    end
  end

  def submit_rating
    if !params[:accurate] or !params[:adequate] or !params[:concise]
      return redirect_to :rate, alert: "Please answer all questions."
    end 

    @rating = Rating.new do |t|
      t.user = @user
      t.comment = @comment
      t.accurate = params[:accurate]
      t.adequate = params[:adequate]
      t.concise = params[:concise]
    end

    #Save rating 
    if @rating.save
      @user.update(current_phase: "compare")
      return redirect_to :experiment
    else
      return redirect_to :rate, alert: 'Something went wrong!'
    end
  end

  def submit_comparison
    if !params[:similarity]
      return redirect_to :rate, alert: "Please indicate the comment similarity."
    end 

    @comparison = Comparison.new do |t|
      t.user = @user
      t.comment1 = @comment1
      t.comment2 = @comment2
      t.similarity = params[:similarity]
    end

    #Save rating 
    if @comparison.save
      @user.increment!(:current_function)
      @user.update(current_phase: "rate")
      return redirect_to :experiment
    else
      return redirect_to :compare, alert: 'Something went wrong!'
    end

  end

  def completed

  end

  private
    def set_user
      if !session[:user_id]
        redirect_to root_path
      else 
        @user = current_user
        if @user.nil?
          log_out
          redirect_to root_path
        end
      end
    end
  
    def check_completed
      if @user.current_function > Function.count
        redirect_to :completed
      end
    end

    def set_function
      @function = Function.find(translate_index(@user.current_function))
    end

    def set_comment
      case @user.group
      when 0
        if @function.id <= Function.count/2
          @comment=Comment.find_by(function:@function, source:"reference")
        else
          @comment=Comment.find_by(function:@function, source:"alex1")
        end
      when 1
        if @function.id <= Function.count/2
          @comment=Comment.find_by(function:@function, source:"alex1")
        else
          @comment=Comment.find_by(function:@function, source:"reference")
        end
      when 2
        if @function.id%2==0
          @comment=Comment.find_by(function:@function, source:"reference")
        else
          @comment=Comment.find_by(function:@function, source:"alex1")
        end
      when 3
        if @function.id%2==0
          @comment=Comment.find_by(function:@function, source:"alex1")
        else
          @comment=Comment.find_by(function:@function, source:"reference")
        end
      when 4
        if (@function.id <= Function.count/2 and @function.id%2==0) or (@function.id > Function.count/2 and @function.id%2==1) 
          @comment=Comment.find_by(function:@function, source:"reference")
        else
          @comment=Comment.find_by(function:@function, source:"alex1")
        end
      when 5
        if (@function.id <= Function.count/2 and @function.id%2==0) or (@function.id > Function.count/2 and @function.id%2==1) 
          @comment=Comment.find_by(function:@function, source:"alex1")
        else
          @comment=Comment.find_by(function:@function, source:"reference")
        end
      end
    end

    def set_comments
      case @user.group
      when 0
        if @function.id <= Function.count/2
          @comment1=Comment.find_by(function:@function, source:"reference")
          @comment2=Comment.find_by(function:@function, source:"alex1")
        else
          @comment1=Comment.find_by(function:@function, source:"alex1")
          @comment2=Comment.find_by(function:@function, source:"reference")
        end
      when 1
        if @function.id <= Function.count/2
          @comment1=Comment.find_by(function:@function, source:"alex1")
          @comment2=Comment.find_by(function:@function, source:"reference")
        else
          @comment1=Comment.find_by(function:@function, source:"reference")
          @comment2=Comment.find_by(function:@function, source:"alex1")
        end
      when 2
        if @function.id%2==0
          @comment1=Comment.find_by(function:@function, source:"reference")
          @comment2=Comment.find_by(function:@function, source:"alex1")
        else
          @comment1=Comment.find_by(function:@function, source:"alex1")
          @comment2=Comment.find_by(function:@function, source:"reference")
        end
      when 3
        if @function.id%2==0
          @comment1=Comment.find_by(function:@function, source:"alex1")
          @comment2=Comment.find_by(function:@function, source:"reference")
        else
          @comment1=Comment.find_by(function:@function, source:"reference")
          @comment2=Comment.find_by(function:@function, source:"alex1")
        end
      when 4
        if (@function.id <= Function.count/2 and @function.id%2==0) or (@function.id > Function.count/2 and @function.id%2==1) 
          @comment1=Comment.find_by(function:@function, source:"reference")
          @comment2=Comment.find_by(function:@function, source:"alex1")
        else
          @comment1=Comment.find_by(function:@function, source:"alex1")
          @comment2=Comment.find_by(function:@function, source:"reference")
        end
      when 5
        if (@function.id <= Function.count/2 and @function.id%2==0) or (@function.id > Function.count/2 and @function.id%2==1) 
          @comment1=Comment.find_by(function:@function, source:"alex1")
          @comment2=Comment.find_by(function:@function, source:"reference")
        else
          @comment1=Comment.find_by(function:@function, source:"reference")
          @comment2=Comment.find_by(function:@function, source:"alex1")
        end
      end
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/compare.html.haml
#content
    .nicebox
        #main_content
            #instructions
                #div{:style=>"display: flex; flex-direction:row; "}
                    #div{:style=>"flex:1; text-align:left"}
                        = link_to "Logout", :logout, :method => :delete
                    #div{:style=>"flex:1"}
                        Function #{@user.current_function}/#{Function.all.count}
                    #div{:style=>"flex:1; text-align:right"}
                        FID #{@function.fid}
                =link_to "View Instructions", :tutorial
            .row
                .column
                    %h2{:style => "line-height:0em;"} Function #{@function.name}
                    %pre
                        %code.language-java.function= @function.text.gsub('<nl>', "\n").gsub('<t>', "\t")
                .column  
                    %h2{:style => "line-height:0em;"} Comment 1
                    .comment= @comment1.text
                    %br
                    %h2{:style => "line-height:0em;"} Comment 2
                    .comment= @comment2.text
                    %br
                    %hr{:style=>"width:100%"}
                    %br

                    %div{:style=> "font-size:1.2em; line-spacing:1.2em;"} Please indicate the level to which you agree with the following statement: 
                    %h3 These two comments are similar. 
                    = form_tag
                    %table.ratings{:style=>"padding:10px 0px; color:#000890"}
                        %tr
                            %td.rtd.sd{:style=>"color:#800000"}
                                = label_tag "similarity_1" do    
                                    Strongly Disagree
                                    %br
                                    %div{:style=>"padding:5px"}= radio_button_tag "similarity", "1"
                            %td.rtd.d{:style=>"color:#786040"}
                                = label_tag "similarity_2" do    
                                    Disagree
                                    %br
                                    %div{:style=>"padding:5px"}= radio_button_tag "similarity", "2"
                            %td.rtd.a{:style=>"color:#486078"}
                                = label_tag "similarity_3" do    
                                    Agree
                                    %br
                                    %div{:style=>"padding:5px"}= radio_button_tag "similarity", "3"
                            
                            %td.rtd.sa{:style=>"color:#000890"}
                                = label_tag "similarity_4" do    
                                    Strongly Agree
                                    %br
                                    %div{:style=>"padding:5px"}= radio_button_tag "similarity", "4"
                    %br
                    
                    %div{:style=>"text-align:right"}= submit_tag "Submit", :id => "submit"
                            

app/views/home/completed.html.haml
#basic_page
    .center_content
        %pre{:style=>"max-width:75%;"}
            %code.function 
                = "public void thanks(){\n\tSystem.out.println(\"Thank you!\"\n\t\t+ \"You have successfully completed all of the tasks.\"\n\t\t+ \"Please contact the study coordinators.\");\n}"
        %br
        %br
        .smallbox
            %div
                = link_to "Logout", :logout, :method => :delete

app/views/home/index.html.haml
#basic_page
    .center_content
        %pre
            %code.function 
                = "public void welcome(){\n\tSystem.out.println(\"Welcome to our Comment-Rating Study!\");\n}"
        %br
        %br
        .smallbox
            %div
                %h3{:style=>"margin-top:0px;"} Login
                = form_for :session, :url => :login do |f|
                    = f.label :email
                    = f.text_field :email
                    %br
                    %br
                    = f.label :password
                    = f.password_field :password
                    %br
                    %br
                    = submit_tag "Submit"
            %div{:style=>"margin-left:15px; font-size:1.5em"}
                ="... or" 
                = link_to "Sign up", signup_url

app/views/home/rate.html.haml
#content
    .nicebox
        #main_content
            #instructions
                #div{:style=>"display: flex; flex-direction:row; "}
                    #div{:style=>"flex:1; text-align:left"}
                        = link_to "Logout", :logout, :method => :delete
                    #div{:style=>"flex:1"}
                        Function #{@user.current_function}/#{Function.all.count}
                    #div{:style=>"flex:1; text-align:right"}
                        FID #{@function.fid}
                =link_to "View Instructions", :tutorial
            .row
                .column    
                    %h2{:style => "line-height:0em;"} Function #{@function.name}
                    %pre{:style=> "width:100%, overflow:scroll"}
                        %code.language-java.function= @function.text.gsub('<nl>', "\n").gsub('<t>', "\t")
                .column  
                    %h2{:style => "line-height:0em;"} Comment
                    .comment= @comment.text

                    %br
                    %hr{:style=>"width:100%"}
                    %br

                    %div{:style=> "font-size:1.2em; line-spacing:1.2em;"} Please indicate the level to which you agree with the following statements: 
                    = form_tag
                    %div{:style=>"width:100%"}
                    %h3 Independent of other factors, I feel that the summary is accurate.
                    %table.ratings{:style=>"flex:1"}
                        %tr
                            %td.rtd.sd{:style=>"color:#800000"}
                                = label_tag "accurate_1" do    
                                    Strongly Disagree
                                    %br
                                    %div{:style=>"padding:5px"}=radio_button_tag "accurate", 1
                            %td.rtd.d{:style=>"color:#786040;"}
                                = label_tag "accurate_2" do    
                                    Disagree
                                    %br
                                    %div{:style=>"padding:5px"}=radio_button_tag "accurate", 2
                            %td.rtd.a{:style=>"color:#486078"}
                                = label_tag "accurate_3" do    
                                    Agree
                                    %br
                                    %div{:style=>"padding:5px"}=radio_button_tag "accurate", 3
                            
                            %td.rtd.sa{:style=>"color:#000890"}
                                = label_tag "accurate_4" do    
                                    Strongly Agree
                                    %br
                                    %div{:style=>"padding:5px"}=radio_button_tag "accurate", 4
                    %h3 The summary is missing important information, and that can hinder the understanding of the method.
                    %table.ratings
                        %tr
                            %td.rtd.sd{:style=>"color:#800000"}
                                = label_tag "adequate_1" do    
                                    Strongly Disagree
                                    %br
                                    %div{:style=>"padding:5px"}=radio_button_tag "adequate", 1
                            %td.rtd.d{:style=>"color:#786040"}
                                = label_tag "adequate_2" do    
                                    Disagree
                                    %br
                                    %div{:style=>"padding:5px"}=radio_button_tag "adequate", 2
                            %td.rtd.a{:style=>"color:#486078"}
                                = label_tag "adequate_3" do    
                                    Agree
                                    %br
                                    %div{:style=>"padding:5px"}=radio_button_tag "adequate", 3
                            %td.rtd.sa{:style=>"color:#000890"}
                                = label_tag "adequate_4" do    
                                    Strongly Agree
                                    %br
                                    %div{:style=>"padding:5px"}=radio_button_tag "adequate", 4
                    %h3 The summary contains a lot of unnecessary information.
                    %table.ratings
                        %tr
                            %td.rtd.sd{:style=>"color:#800000"}
                                = label_tag "concise_1" do    
                                    Strongly Disagree
                                    %br
                                    %div{:style=>"padding:5px"}= radio_button_tag "concise", 1
                            %td.rtd.d{:style=>"color:#786040"}
                                = label_tag "concise_2" do    
                                    Disagree
                                    %br
                                    %div{:style=>"padding:5px"}=radio_button_tag "concise", 2
                            %td.rtd.a{:style=>"color:#486078"}
                                = label_tag "concise_3" do    
                                    Agree
                                    %br
                                    %div{:style=>"padding:5px"}=radio_button_tag "concise", 3
                            %td.rtd.sa{:style=>"color:#000890"}
                                = label_tag "concise_4" do    
                                    Strongly Agree
                                    %br
                                    %div{:style=>"padding:5px"}=radio_button_tag "concise", 4
                    %br
                    
                    %div{:style=>"text-align:right"}= submit_tag "Submit", :id => "submit"
                            

app/views/home/welcome.html.haml
%h2 AAAHHHHH